# Generated by Django 5.0.14 on 2026-07-17 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Elite', 'Elite')], max_length=20)),
                ('plan_slug', models.CharField(choices=[('gold', 'gold'), ('platinum', 'platinum'), ('elite', 'elite')], db_index=True, max_length=20)),
                ('views_limit', models.PositiveIntegerField()),
                ('views_used', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_subscriptions',
                'ordering': ('-end_date', '-created_at'),
                'indexes': [models.Index(fields=['user', 'end_date'], name='membership_sub_user_end_idx')],
            },
        ),
    ]
