# Generated by Django 5.0.14 on 2026-09-09 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'active'], name='notificatio_user_id_f8e28c_idx'),
        ),
    ]
