# Generated by Django 5.0.14 on 2026-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
            ],
            options={
                'verbose_name': 'member profile',
                'verbose_name_plural': 'member profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.memberprofile',),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
            ],
            options={
                'verbose_name': 'profile photo',
                'verbose_name_plural': 'profile photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.memberphoto',),
        ),
    ]
