# Generated by Django 5.0.14 on 2026-07-17 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('thumbnail_data', models.BinaryField()),
                ('mime_type', models.CharField(default='image/webp', max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('original_size_bytes', models.PositiveBigIntegerField()),
                ('compressed_size_bytes', models.PositiveBigIntegerField()),
                ('thumbnail_size_bytes', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(default=1200)),
                ('height', models.PositiveIntegerField(default=1500)),
                ('thumbnail_width', models.PositiveIntegerField(default=240)),
                ('thumbnail_height', models.PositiveIntegerField(default=300)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photos_v2', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profile_photos_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_photos_v2',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='profile_pho_user_id_eb4076_idx'), models.Index(fields=['user', 'is_primary'], name='profile_pho_user_id_9e91b2_idx'), models.Index(fields=['checksum'], name='profile_pho_checksu_8573c3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profilephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='one_primary_profile_photo_per_user_v2'),
        ),
    ]
