# Generated by Django 5.0.14 on 2026-07-17

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Finish the BYTEA model before the legacy ImageField table is removed."""

    dependencies = [
        ("accounts", "0013_user"),
        ("profiles", "0002_delete_profilephoto_delete_memberprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePhotoAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("photo_id", models.UUIDField(db_index=True)),
                ("member_id", models.UUIDField(db_index=True)),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_type", models.CharField(blank=True, max_length=30)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("REPLACED", "Replaced"),
                            ("DELETED", "Deleted"),
                            ("SET_PRIMARY", "Set primary"),
                            ("REORDERED", "Reordered"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "profile_photo_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="profilephoto",
            name="one_primary_profile_photo_per_user_v2",
        ),
        migrations.RemoveIndex(
            model_name="profilephoto",
            name="profile_pho_checksu_8573c3_idx",
        ),
        migrations.RenameIndex(
            model_name="profilephoto",
            new_name="profile_pho_user_id_1b7564_idx",
            old_name="profile_pho_user_id_eb4076_idx",
        ),
        migrations.RenameIndex(
            model_name="profilephoto",
            new_name="profile_pho_user_id_a9e2e8_idx",
            old_name="profile_pho_user_id_9e91b2_idx",
        ),
        migrations.RemoveField(model_name="profilephoto", name="verified_by"),
        migrations.AddField(
            model_name="profilephoto",
            name="verified_by_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_profile_photos",
                to="accounts.admin",
            ),
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="verified_by_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_profile_photos",
                to="accounts.staff",
            ),
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="verified_by_super_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_profile_photos",
                to="accounts.superadmin",
            ),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="one_primary_profile_photo_per_user",
            ),
        ),
        migrations.AlterModelTable(name="profilephoto", table="profile_photos"),
        migrations.AddIndex(
            model_name="profilephotoauditlog",
            index=models.Index(
                fields=["member_id", "created_at"],
                name="profile_pho_member__7dcb02_idx",
            ),
        ),
    ]
