# Generated by Django 5.0.14 on 2026-07-17 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilephotoauditlog_legacy_source_purged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('thumbnail_data', models.BinaryField()),
                ('mime_type', models.CharField(default='image/webp', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
