# Generated by Django 5.0.14 on 2026-07-15 07:15

import apps.accounts.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('features', models.JSONField(default=list)),
                ('highlighted', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'membership_plans',
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couple_names', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('story', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'db_table': 'success_stories',
            },
        ),
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('plan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by_super_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_requests', to='accounts.superadmin')),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.staff')),
                ('escalated_to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.admin')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='accounts.customersupportagent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_enquiries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='MemberMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershipplan')),
            ],
            options={
                'db_table': 'member_memberships',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=12)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.admin')),
                ('member_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('staff_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.staff')),
                ('super_admin_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.superadmin')),
                ('support_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.customersupportagent')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], db_index=True, default='PENDING', max_length=24)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_status', models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NONE', max_length=12)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_reference', models.CharField(blank=True, max_length=120)),
                ('refund_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.membermembership')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.membershipplan')),
                ('refunded_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='accounts.admin')),
                ('refunded_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='accounts.superadmin')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to='accounts.superadmin')),
            ],
            options={
                'db_table': 'platform_settings',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_reports', to='accounts.admin')),
                ('reviewed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_reports', to='accounts.staff')),
            ],
            options={
                'db_table': 'profile_reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfileVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('FULL_PROFILE', 'Full profile'), ('PROFILE_PHOTO', 'Profile photo'), ('IDENTITY_DOCUMENT', 'Identity document'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('EDUCATION', 'Education'), ('EMPLOYMENT', 'Employment')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('ESCALATED', 'Escalated')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_verification_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfileVerificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_status_changes', to='accounts.admin')),
                ('changed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_status_changes', to='accounts.staff')),
                ('changed_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_status_changes', to='accounts.superadmin')),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.profileverificationrequest')),
            ],
            options={
                'db_table': 'profile_verification_history',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfileVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_links', to='accounts.memberdocument')),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='core.profileverificationrequest')),
            ],
            options={
                'db_table': 'profile_verification_documents',
            },
        ),
        migrations.CreateModel(
            name='ProfileVerificationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_assignments_made', to='accounts.admin')),
                ('assigned_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_assignments_made', to='accounts.superadmin')),
                ('assigned_to_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_assignments', to='accounts.staff')),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.profileverificationrequest')),
            ],
            options={
                'db_table': 'profile_verification_assignments',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=12)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='core.payment')),
                ('processed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_processed', to='accounts.admin')),
                ('processed_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_processed', to='accounts.superadmin')),
                ('requested_by_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportSlaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=10)),
                ('first_response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=2880)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_rules', to='core.supportcategory')),
            ],
            options={
                'db_table': 'support_sla_rules',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_MEMBER', 'Waiting for member'), ('WAITING_FOR_INTERNAL', 'Waiting for internal'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, default='UNASSIGNED', max_length=30)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('PHONE', 'Phone'), ('SYSTEM', 'System'), ('EMAIL', 'Email (disabled)'), ('WHATSAPP', 'WhatsApp (disabled)')], default='WEB', max_length=12)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.supportcategory')),
                ('created_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_created', to='accounts.customersupportagent')),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='accounts.customersupportagent')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
                ('related_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_replies', to=settings.AUTH_USER_MODEL)),
                ('support_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_replies', to='accounts.customersupportagent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_replies',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='support_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportticket')),
                ('uploaded_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_attachments', to='accounts.customersupportagent')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportticketreply')),
            ],
            options={
                'db_table': 'support_ticket_attachments',
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_reason', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_made', to='accounts.admin')),
                ('assigned_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_made', to='accounts.superadmin')),
                ('assigned_to_support_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to='accounts.customersupportagent')),
                ('claimed_by_support_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_claimed', to='accounts.customersupportagent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.supportticket')),
            ],
            options={
                'db_table': 'ticket_assignments',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_feedback', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.supportticket')),
            ],
            options={
                'db_table': 'ticket_feedback',
            },
        ),
        migrations.CreateModel(
            name='TicketInternalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_internal_notes', to='accounts.admin')),
                ('super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_internal_notes', to='accounts.superadmin')),
                ('support_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_internal_notes', to='accounts.customersupportagent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='core.supportticket')),
            ],
            options={
                'db_table': 'ticket_internal_notes',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('OPEN', 'Open'), ('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_MEMBER', 'Waiting for member'), ('WAITING_FOR_INTERNAL', 'Waiting for internal'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], max_length=30)),
                ('new_status', models.CharField(choices=[('OPEN', 'Open'), ('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_MEMBER', 'Waiting for member'), ('WAITING_FOR_INTERNAL', 'Waiting for internal'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to='accounts.admin')),
                ('changed_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('changed_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to='accounts.superadmin')),
                ('changed_by_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to='accounts.customersupportagent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.supportticket')),
            ],
            options={
                'db_table': 'ticket_status_history',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_sender_receiver_interest'),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='interest_sender_not_receiver'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', False), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', True), ('support_recipient__isnull', True)), models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', True), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', False), ('support_recipient__isnull', True)), models.Q(('admin_recipient__isnull', False), ('member_recipient__isnull', True), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', True), ('support_recipient__isnull', True)), models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', True), ('staff_recipient__isnull', False), ('super_admin_recipient__isnull', True), ('support_recipient__isnull', True)), models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', True), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', True), ('support_recipient__isnull', False)), _connector='OR'), name='notification_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='profileverificationhistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('changed_by_admin__isnull', True), ('changed_by_staff__isnull', False), ('changed_by_super_admin__isnull', True)), models.Q(('changed_by_admin__isnull', False), ('changed_by_staff__isnull', True), ('changed_by_super_admin__isnull', True)), models.Q(('changed_by_admin__isnull', True), ('changed_by_staff__isnull', True), ('changed_by_super_admin__isnull', False)), _connector='OR'), name='verification_history_exactly_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='profileverificationdocument',
            constraint=models.UniqueConstraint(fields=('verification_request', 'member_document'), name='unique_verification_document_link'),
        ),
        migrations.AddConstraint(
            model_name='profileverificationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('verification_request',), name='one_current_verification_assignment'),
        ),
        migrations.AddConstraint(
            model_name='profileverificationassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assigned_by_admin__isnull', False), ('assigned_by_super_admin__isnull', True)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', False)), _connector='OR'), name='verification_assignment_exactly_one_assigner'),
        ),
        migrations.AddConstraint(
            model_name='supportslarule',
            constraint=models.UniqueConstraint(fields=('category', 'priority'), name='unique_support_sla_category_priority'),
        ),
        migrations.AddConstraint(
            model_name='supportticketreply',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('member_sender__isnull', False), ('support_sender__isnull', True)), models.Q(('member_sender__isnull', True), ('support_sender__isnull', False)), _connector='OR'), name='support_reply_exactly_one_sender'),
        ),
        migrations.AddConstraint(
            model_name='supportticketattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('uploaded_by_member__isnull', False), ('uploaded_by_support__isnull', True)), models.Q(('uploaded_by_member__isnull', True), ('uploaded_by_support__isnull', False)), _connector='OR'), name='support_attachment_exactly_one_uploader'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('ticket',), name='one_current_ticket_assignment'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assigned_by_admin__isnull', False), ('assigned_by_super_admin__isnull', True), ('claimed_by_support_agent__isnull', True)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', False), ('claimed_by_support_agent__isnull', True)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', True), ('claimed_by_support_agent__isnull', False)), _connector='OR'), name='ticket_assignment_exactly_one_assigner'),
        ),
        migrations.AddConstraint(
            model_name='ticketinternalnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin__isnull', True), ('super_admin__isnull', True), ('support_agent__isnull', False)), models.Q(('admin__isnull', False), ('super_admin__isnull', True), ('support_agent__isnull', True)), models.Q(('admin__isnull', True), ('super_admin__isnull', False), ('support_agent__isnull', True)), _connector='OR'), name='ticket_note_exactly_one_author'),
        ),
        migrations.AddConstraint(
            model_name='ticketstatushistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('changed_by_admin__isnull', False), ('changed_by_member__isnull', True), ('changed_by_super_admin__isnull', True), ('changed_by_support__isnull', True)), models.Q(('changed_by_admin__isnull', True), ('changed_by_member__isnull', True), ('changed_by_super_admin__isnull', True), ('changed_by_support__isnull', False)), models.Q(('changed_by_admin__isnull', True), ('changed_by_member__isnull', True), ('changed_by_super_admin__isnull', False), ('changed_by_support__isnull', True)), models.Q(('changed_by_admin__isnull', True), ('changed_by_member__isnull', False), ('changed_by_super_admin__isnull', True), ('changed_by_support__isnull', True)), _connector='OR'), name='ticket_history_exactly_one_actor'),
        ),
    ]
