# Generated by Django 5.0.14 on 2026-07-15 08:47

import uuid
from django.db import migrations, models


def seed_plans(apps, schema_editor):
    MembershipPlan = apps.get_model('core', 'MembershipPlan')
    plans = [
        {
            'name': 'Gold',
            'slug': 'gold',
            'price': 2999.00,
            'duration': '3 Months',
            'highlighted': False,
            'badge': '',
            'color': 'from-amber-500 to-yellow-600',
            'features': [
                'Everything in Free',
                'Unlimited interests',
                'Advanced search filters',
                'View all photos',
                'Direct messaging',
                'Profile highlighting',
                'Email support',
            ],
        },
        {
            'name': 'Platinum',
            'slug': 'platinum',
            'price': 5999.00,
            'duration': '6 Months',
            'highlighted': True,
            'badge': '✦ Most Popular',
            'color': 'from-blue-500 to-indigo-600',
            'features': [
                'Everything in Gold',
                'AI matchmaking engine',
                'Priority profile visibility',
                'Video call feature',
                'Relationship manager',
                'Profile verification status',
                'Phone support',
                'Horoscope matching',
            ],
        },
        {
            'name': 'Elite',
            'slug': 'elite',
            'price': 14999.00,
            'duration': '12 Months',
            'highlighted': False,
            'badge': '✦ Premium',
            'color': 'from-slate-800 to-slate-950',
            'features': [
                'Everything in Platinum',
                'Dedicated matchmaker',
                'Premium profile showcase',
                'Background verification',
                'Concierge service',
                'Exclusive events access',
                'Priority 24/7 support',
                'Guaranteed matches',
                'Wedding planning assistance',
            ],
        }
    ]
    for plan_data in plans:
        MembershipPlan.objects.update_or_create(
            slug=plan_data['slug'],
            defaults={
                'name': plan_data['name'],
                'price': plan_data['price'],
                'duration': plan_data['duration'],
                'features': plan_data['features'],
                'highlighted': plan_data['highlighted'],
                'badge': plan_data['badge'],
                'color': plan_data['color'],
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_support_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_webhook_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]

