# Generated by Django 5.0.14 on 2026-07-15 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_employee_code_and_more'),
        ('core', '0003_paymentwebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('PROFILE_VERIFICATION', 'Profile verification'), ('PHOTO_VERIFICATION', 'Photo verification'), ('DOCUMENT_VERIFICATION', 'Document verification'), ('COMPLAINT_REVIEW', 'Complaint review'), ('PROFILE_REPORT_REVIEW', 'Profile report review'), ('MODERATION_TASK', 'Moderation task')], max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING', 'Waiting'), ('ESCALATED', 'Escalated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNASSIGNED', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments_made', to='accounts.admin')),
                ('assigned_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments_made', to='accounts.superadmin')),
                ('assigned_to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to='accounts.staff')),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='core.complaint')),
                ('related_document_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='accounts.memberdocument')),
                ('related_profile_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='core.profilereport')),
                ('related_profile_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='core.profileverificationrequest')),
            ],
            options={
                'db_table': 'work_assignments',
                'ordering': ('-created_at',),
            },
        ),
    ]
