# Generated by Django 5.0.14 on 2026-07-15 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('view_date', models.DateField(db_index=True, help_text='UTC calendar date of the view.')),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_view_logs',
                'ordering': ('-viewed_at',),
                'indexes': [models.Index(fields=['viewer', 'view_date'], name='profile_view_log_viewer_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='profileviewlog',
            constraint=models.CheckConstraint(check=models.Q(('viewer', models.F('viewed')), _negated=True), name='profile_view_log_viewer_not_viewed'),
        ),
    ]
