# Generated by Django 5.0.14 on 2026-07-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customersupportagent_specializations_and_more'),
        ('core', '0006_assignmentstrategy_queue_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentaudit',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='employeeavailability',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ticketassignmenthistory',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='employee',
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_audits', to='accounts.customersupportagent'),
        ),
        migrations.AddField(
            model_name='assignmentaudit',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_audits', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='staff_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='support_agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.customersupportagent'),
        ),
        migrations.AddField(
            model_name='ticketassignmenthistory',
            name='assigned_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_delegated', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='ticketassignmenthistory',
            name='assigned_by_super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_delegated', to='accounts.superadmin'),
        ),
        migrations.AddField(
            model_name='workload',
            name='staff_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='workload',
            name='support_agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='accounts.customersupportagent'),
        ),
        migrations.AlterField(
            model_name='ticketassignmenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignment_history', to='accounts.customersupportagent'),
        ),
    ]
