# Generated by Django 5.0.14 on 2026-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customersupportagent_specializations_and_more'),
        ('core', '0007_remove_assignmentaudit_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profileverificationassignment',
            name='verification_assignment_exactly_one_assigner',
        ),
        migrations.AddConstraint(
            model_name='profileverificationassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assigned_by_admin__isnull', False), ('assigned_by_super_admin__isnull', True)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', False)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', True)), _connector='OR'), name='verification_assignment_exactly_one_assigner_or_system'),
        ),
    ]
