# Generated by Django 5.0.14 on 2026-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='can_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_use_advanced_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_use_horoscope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='contact_access_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('MUTUAL_ONLY', 'Mutual Only'), ('FULL', 'Full')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='interest_limit_daily',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='message_limit_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='photo_access_mode',
            field=models.CharField(choices=[('PRIMARY_ONLY', 'Primary Only'), ('ALL_APPROVED', 'All Approved')], default='PRIMARY_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='profile_boost_level',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='profile_view_limit_daily',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='support_priority',
            field=models.CharField(default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
