# Generated by Django 5.0.14 on 2026-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_membershiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='membershiprequest',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='approved_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='rejected_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
