# Generated by Django 5.0.14 on 2026-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_membershiprequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermembership',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAYMENT_PENDING', 'Payment Pending'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='FREE', max_length=30),
        ),
        migrations.AlterField(
            model_name='membermembership',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
