# Generated by Django 5.0.14 on 2026-07-16 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_membermembership_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='can_get_priority_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_send_interest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_use_profile_boost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_view_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_view_private_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='can_view_profile_visitors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='contact_unlock_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='daily_message_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='daily_profile_unlock_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='interest_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='monthly_profile_unlock_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfileUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('usage_date', models.DateField(db_index=True)),
                ('consumed_limit', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_unlocks', to='core.membermembership')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_unlocks_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_unlocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_unlocks',
                'ordering': ('-unlocked_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='profileunlock',
            constraint=models.UniqueConstraint(fields=('viewer', 'profile', 'usage_date'), name='unique_viewer_profile_usage_date'),
        ),
        migrations.AddConstraint(
            model_name='profileunlock',
            constraint=models.CheckConstraint(check=models.Q(('viewer', models.F('profile')), _negated=True), name='profile_unlock_viewer_not_profile'),
        ),
    ]
