# Generated by Django 5.0.14 on 2026-07-16 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_membershipplan_can_get_priority_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_blocks',
            },
        ),
        migrations.AddConstraint(
            model_name='profileblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_blocker_blocked'),
        ),
        migrations.AddConstraint(
            model_name='profileblock',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_blocker_not_blocked'),
        ),
    ]
