# Generated by Django 5.0.14 on 2026-07-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profileblock_profileblock_unique_blocker_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='messaging_mode',
            field=models.CharField(choices=[('DISABLED', 'disabled'), ('MUTUAL_ONLY', 'mutual_only'), ('ENABLED', 'enabled')], default='DISABLED', max_length=20),
        ),
    ]
