# Generated by Django 5.0.14 on 2026-07-18

from django.db import migrations, models


def enable_received_interests_for_paid_plans(apps, schema_editor):
    MembershipPlan = apps.get_model('core', 'MembershipPlan')
    MembershipPlan.objects.filter(price__gt=0).update(can_view_received_interests=True)


def disable_received_interests_for_paid_plans(apps, schema_editor):
    MembershipPlan = apps.get_model('core', 'MembershipPlan')
    MembershipPlan.objects.filter(price__gt=0).update(can_view_received_interests=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_membermembership_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='can_view_received_interests',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            enable_received_interests_for_paid_plans,
            disable_received_interests_for_paid_plans,
        ),
    ]
