# Generated by Django 5.0.14 on 2026-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_membershipplan_fk_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileverificationhistory',
            name='new_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profileverificationhistory',
            name='old_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], max_length=20),
        ),
    ]
