# Generated by Django 5.0.14 on 2026-07-20 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_profileverificationhistory_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=255)),
                ('processing_status', models.CharField(default='received', max_length=50)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'razorpay_webhook_events',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='advanced_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='contact_access_level',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='direct_messaging_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='razorpay_plan_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_order_number', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(default='created', max_length=50)),
                ('receipt', models.CharField(max_length=100)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('attempt_number', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='core.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('method', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('vpa_masked', models.CharField(blank=True, max_length=100, null=True)),
                ('card_network', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=10, null=True)),
                ('email_masked', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_masked', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('error_source', models.CharField(blank=True, max_length=100, null=True)),
                ('error_step', models.CharField(blank=True, max_length=100, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('duration_days_snapshot', models.IntegerField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_purchases', to='core.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_purchases', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_purchases', to='core.paymenttransaction', unique=True)),
            ],
            options={
                'db_table': 'membership_purchases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('internal_refund_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('speed', models.CharField(default='normal', max_length=50)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.paymenttransaction')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_order_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_transaction_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='refund_amount_gt_zero'),
        ),
    ]
