# Generated by Django 5.0.14 on 2026-07-20 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_baseaccount_last_seen_at'),
        ('core', '0026_razorpaywebhookevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Rename the legacy RefundRequest model to LegacyRefundRequest (keeps table 'refund_requests' intact)
        migrations.RenameModel(
            old_name='RefundRequest',
            new_name='LegacyRefundRequest',
        ),

        # 2. Create the new RefundRequest model mapping to 'payment_refund_requests'
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='core.paymenttransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_refund_requests',
                'ordering': ('-requested_at',),
            },
        ),

        # 3. Create the new RefundTransaction model
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('internal_refund_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='core.paymenttransaction')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.refundrequest')),
            ],
            options={
                'db_table': 'refund_transactions',
                'ordering': ('-created_at',),
            },
        ),

        # 4. Alterations on existing tables
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='raw_metadata',
            new_name='safe_metadata',
        ),
        migrations.RenameField(
            model_name='razorpaywebhookevent',
            old_name='processing_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='email_masked',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='phone_masked',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='amount_subunits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='duration_days_snapshot',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='plan_name_snapshot',
            field=models.CharField(default='Base', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='plan_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

        # 5. Constraints
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(check=models.Q(('requested_amount__gt', 0)), name='refund_request_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='refundtransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='refund_transaction_amount_gt_zero'),
        ),

        # 6. Delete temporary model Refund
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
