# Generated by Django 5.0.14 on 2026-07-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_migrate_legacy_payment_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippurchase',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_purchases', to='core.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount_subunits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='duration_days_snapshot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan_name_snapshot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan_price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
