# Generated by Django 5.0.14 on 2026-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_support_attachment_db_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='discount_1y',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='discount_3m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='discount_6m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='price_1y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='price_3m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='price_6m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
