# Generated by Django 5.0.14 on 2026-07-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_dead_columns_and_optional_message_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentrule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assignmentrule',
            name='designation',
        ),
    ]
