# Generated by Django 5.0.14 on 2026-07-24 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_adminactivitylog_city_adminactivitylog_country_and_more'),
        ('core', '0038_remove_assignmentrule_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTicketReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.UUIDField(db_index=True)),
                ('admin_type', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CUSTOMER_SUPPORT', 'Customer Support')], max_length=30)),
                ('last_read_message_id', models.UUIDField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_ticket_read_states',
            },
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_CLAIMED', 'Ticket claimed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_REASSIGNED', 'Ticket reassigned'), ('TICKET_UNASSIGNED', 'Ticket unassigned'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_REOPENED', 'Ticket reopened'), ('TICKET_CLOSED', 'Ticket closed'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('REPLY_SENT', 'Reply sent'), ('INTERNAL_NOTE_ADDED', 'Internal note added'), ('ATTACHMENT_ADDED', 'Attachment added')], db_index=True, max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ticket_audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='claimed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tickets', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='claimed_by_super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tickets', to='accounts.superadmin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='claimed_by_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tickets', to='accounts.customersupportagent'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_by_super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to='accounts.superadmin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_by_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to='accounts.customersupportagent'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_by_super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='accounts.superadmin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_by_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='accounts.customersupportagent'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Optimistic lock for concurrent updates'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='ticket_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'last_reply_at'], name='ticket_status_lastreply_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['current_assignee', 'status'], name='ticket_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['sla_deadline'], name='ticket_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['member', 'status'], name='ticket_member_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='ticket_number_lookup_idx'),
        ),
        migrations.AddField(
            model_name='adminticketreadstate',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.supportticket'),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.supportticket'),
        ),
        migrations.AddIndex(
            model_name='adminticketreadstate',
            index=models.Index(fields=['admin_id', 'admin_type'], name='readstate_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='adminticketreadstate',
            index=models.Index(fields=['ticket', 'unread_count'], name='readstate_ticket_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminticketreadstate',
            constraint=models.UniqueConstraint(fields=('admin_id', 'admin_type', 'ticket'), name='unique_admin_ticket_read_state'),
        ),
        migrations.AddIndex(
            model_name='ticketauditlog',
            index=models.Index(fields=['ticket', 'created_at'], name='auditlog_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketauditlog',
            index=models.Index(fields=['actor_id', 'action'], name='auditlog_actor_action_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketauditlog',
            index=models.Index(fields=['action', 'created_at'], name='auditlog_action_created_idx'),
        ),
    ]
