# Generated by Django 5.0.14 on 2026-07-25 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_customersupportaccessscope_account_and_more'),
        ('core', '0039_support_refactor_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_exactly_one_recipient',
        ),
        migrations.RemoveConstraint(
            model_name='supportticketattachment',
            name='support_attachment_exactly_one_uploader',
        ),
        migrations.RemoveConstraint(
            model_name='supportticketreply',
            name='support_reply_exactly_one_sender',
        ),
        migrations.RemoveConstraint(
            model_name='ticketassignment',
            name='ticket_assignment_exactly_one_assigner',
        ),
        migrations.RemoveConstraint(
            model_name='ticketinternalnote',
            name='ticket_note_exactly_one_author',
        ),
        migrations.RemoveConstraint(
            model_name='ticketstatushistory',
            name='ticket_history_exactly_one_actor',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='ticket_assignee_status_idx',
        ),
        migrations.RemoveField(
            model_name='assignmentaudit',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='contactenquiry',
            name='assigned_to_support',
        ),
        migrations.RemoveField(
            model_name='employeeavailability',
            name='support_agent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='support_recipient',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='claimed_by_support',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='closed_by_support',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='created_by_support',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='current_assignee',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='resolved_by_support',
        ),
        migrations.RemoveField(
            model_name='supportticketattachment',
            name='uploaded_by_support',
        ),
        migrations.RemoveField(
            model_name='supportticketreply',
            name='support_sender',
        ),
        migrations.RemoveField(
            model_name='ticketassignment',
            name='assigned_to_support_agent',
        ),
        migrations.RemoveField(
            model_name='ticketassignment',
            name='claimed_by_support_agent',
        ),
        migrations.RemoveField(
            model_name='ticketassignmenthistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ticketinternalnote',
            name='support_agent',
        ),
        migrations.RemoveField(
            model_name='ticketstatushistory',
            name='changed_by_support',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='support_agent',
        ),
        migrations.AlterField(
            model_name='adminticketreadstate',
            name='admin_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', False), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', True)), models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', True), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', False)), models.Q(('admin_recipient__isnull', False), ('member_recipient__isnull', True), ('staff_recipient__isnull', True), ('super_admin_recipient__isnull', True)), models.Q(('admin_recipient__isnull', True), ('member_recipient__isnull', True), ('staff_recipient__isnull', False), ('super_admin_recipient__isnull', True)), _connector='OR'), name='notification_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='supportticketattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('uploaded_by_admin__isnull', True), ('uploaded_by_member__isnull', False), ('uploaded_by_super_admin__isnull', True)), models.Q(('uploaded_by_admin__isnull', False), ('uploaded_by_member__isnull', True), ('uploaded_by_super_admin__isnull', True)), models.Q(('uploaded_by_admin__isnull', True), ('uploaded_by_member__isnull', True), ('uploaded_by_super_admin__isnull', False)), _connector='OR'), name='support_attachment_exactly_one_uploader'),
        ),
        migrations.AddConstraint(
            model_name='supportticketreply',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin_sender__isnull', True), ('member_sender__isnull', False), ('super_admin_sender__isnull', True)), models.Q(('admin_sender__isnull', False), ('member_sender__isnull', True), ('super_admin_sender__isnull', True)), models.Q(('admin_sender__isnull', True), ('member_sender__isnull', True), ('super_admin_sender__isnull', False)), _connector='OR'), name='support_reply_exactly_one_sender'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assigned_by_admin__isnull', False), ('assigned_by_super_admin__isnull', True)), models.Q(('assigned_by_admin__isnull', True), ('assigned_by_super_admin__isnull', False)), _connector='OR'), name='ticket_assignment_exactly_one_assigner'),
        ),
        migrations.AddConstraint(
            model_name='ticketinternalnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin__isnull', False), ('super_admin__isnull', True)), models.Q(('admin__isnull', True), ('super_admin__isnull', False)), _connector='OR'), name='ticket_note_exactly_one_author'),
        ),
        migrations.AddConstraint(
            model_name='ticketstatushistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('changed_by_admin__isnull', False), ('changed_by_member__isnull', True), ('changed_by_super_admin__isnull', True)), models.Q(('changed_by_admin__isnull', True), ('changed_by_member__isnull', True), ('changed_by_super_admin__isnull', False)), models.Q(('changed_by_admin__isnull', True), ('changed_by_member__isnull', False), ('changed_by_super_admin__isnull', True)), _connector='OR'), name='ticket_history_exactly_one_actor'),
        ),
    ]
