# Generated by Django 5.0.14 on 2026-07-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_notification_notification_exactly_one_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='SuccessStory',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
