# Generated by Django 5.0.14 on 2026-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_delete_blogpost_delete_successstory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='evidence_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
