# Generated by Django 5.0.14 on 2026-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_profilereport_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolver_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolver_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
