# Generated by Django 5.0.14 on 2026-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_supportticket_is_read_supportticket_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='resolver_custom_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolver_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolver_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
