# Generated by Django 5.0.14 on 2026-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_chatmessage_chat_sender_recv_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
            ],
            options={
                'verbose_name': 'direct message',
                'verbose_name_plural': 'direct messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.chatmessage',),
        ),
    ]
