# Generated by Django 5.0.14 on 2026-07-17 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_user'),
        ('core', '0017_chatmessage_chat_sender_recv_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInterest',
            fields=[
            ],
            options={
                'verbose_name': 'member interest',
                'verbose_name_plural': 'member interests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.interest',),
        ),
        migrations.CreateModel(
            name='MemberShortlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='accounts.memberprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_shortlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_shortlists',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='membershortlist',
            constraint=models.UniqueConstraint(fields=('user', 'profile'), name='unique_member_shortlist'),
        ),
    ]
