# Generated by Django 5.0.14 on 2026-07-15 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_seed_data',
            field=models.BooleanField(db_index=True, default=False, help_text='True only for development seed members. Never set in production.'),
        ),
        migrations.CreateModel(
            name='DuplicateAccountFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('EMAIL_EXACT', 'Exact email match'), ('MOBILE_EXACT', 'Exact mobile match'), ('PHOTO_HASH', 'Photo hash match'), ('NAME_DOB_GENDER', 'Name + DOB + gender match'), ('DOCUMENT_HASH', 'Document hash match'), ('DEVICE_FINGERPRINT', 'Device fingerprint match')], db_index=True, max_length=30)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed duplicate'), ('DISMISSED', 'Dismissed (false positive)'), ('MERGED', 'Merged / resolved')], db_index=True, default='PENDING', max_length=20)),
                ('similarity_score', models.FloatField(default=1.0, help_text='Confidence score 0.0-1.0 (1.0 = exact match).')),
                ('match_detail', models.JSONField(blank=True, default=dict, help_text='Structured details about the matched fields.')),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_detected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_as_duplicate', to=settings.AUTH_USER_MODEL)),
                ('primary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_as_primary', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_flags', to='accounts.admin')),
                ('reviewed_by_super_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_flags', to='accounts.superadmin')),
            ],
            options={
                'db_table': 'duplicate_account_flags',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='duplicateaccountflag',
            constraint=models.CheckConstraint(check=models.Q(('primary_member', models.F('duplicate_member')), _negated=True), name='duplicate_flag_different_members'),
        ),
        migrations.AddConstraint(
            model_name='duplicateaccountflag',
            constraint=models.UniqueConstraint(fields=('primary_member', 'duplicate_member', 'flag_type'), name='unique_duplicate_flag_per_type'),
        ),
    ]
