# Generated by Django 5.0.14 on 2026-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_seed_data_duplicate_flag_profile_view_log'),
        ('core', '0006_assignmentstrategy_queue_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportagent',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='support_agents', to='core.specialization'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='core.specialization'),
        ),
    ]
