# Generated by Django 5.0.14 on 2026-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_branch_city_country_admin_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='chat_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersupportagent',
            name='chat_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='chat_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='chat_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='chat_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
