# Generated by Django 5.0.14 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_admin_chat_public_key_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_object_id', models.UUIDField(db_index=True)),
                ('actor_object_id', models.UUIDField(blank=True, null=True)),
                ('previous_permissions', models.JSONField(blank=True, default=dict)),
                ('new_permissions', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actor_logs_ct', to='contenttypes.contenttype')),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs_ct', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'permission_audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_object_id', models.UUIDField(db_index=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('assigned_by_object_id', models.UUIDField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions_ct', to='contenttypes.contenttype')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='accounts.adminpermission')),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_ct', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'user_permissions',
                'ordering': ('permission__code',),
            },
        ),
        migrations.AddConstraint(
            model_name='userpermission',
            constraint=models.UniqueConstraint(fields=('user_content_type', 'user_object_id', 'permission'), name='unique_user_permission_override'),
        ),
    ]
