# Generated by Django 5.0.14 on 2026-07-16 09:58

from django.db import migrations


def run_seed_rbac(apps, schema_editor):
    from apps.accounts.rbac import seed_rbac
    seed_rbac()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permissionauditlog_userpermission_and_more'),
    ]

    operations = [
        migrations.RunPython(run_seed_rbac, migrations.RunPython.noop),
    ]

