# Generated by Django 5.0.14 on 2026-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_new_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='reviewed_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
