# Generated by Django 5.0.14 on 2026-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_memberdocument_reviewed_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_status',
            field=models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='NOT_UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberphoto',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20),
        ),
    ]
