# Generated by Django 5.0.14 on 2026-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_member_account_status_alter_member_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
