# Generated by Django 5.0.14 on 2026-07-17 06:52

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.member',),
            managers=[
                ('objects', apps.accounts.models.AccountManager()),
            ],
        ),
    ]
