# Generated by Django 5.0.14 on 2026-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_standardize_verification_statuses'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='member_verification_status_idx',
        ),
        migrations.AlterField(
            model_name='member',
            name='document_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='not_started', max_length=20),
        ),
    ]
