# Generated by Django 5.0.14 on 2026-07-19 11:52

import apps.accounts.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_memberdocument_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_role', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document review histories',
                'db_table': 'document_review_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='archived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_versions', to='accounts.memberdocument'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='document_number',
            field=models.CharField(blank=True, help_text='Masked document number e.g. XXXX-XXXX-1234', max_length=100),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='reviewer_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to admin/staff'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='uploaded_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file_path',
            field=models.FileField(blank=True, null=True, storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='member_documents/'),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='memberdocument',
            index=models.Index(fields=['member', 'status'], name='member_docu_member__5f8afd_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdocument',
            index=models.Index(fields=['member', 'document_type', '-uploaded_at'], name='member_docu_member__ed529b_idx'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='accounts.memberdocument'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_review_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
