# Generated by Django 5.0.14 on 2026-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_old_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='compressed_size',
            field=models.IntegerField(blank=True, help_text='Size of the stored compressed bytes.', null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='Gzip-compressed document bytes stored in the database.', null=True),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file_size',
            field=models.IntegerField(help_text='Original uncompressed file size in bytes.'),
        ),
    ]
