# Generated by Django 5.0.14 on 2026-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_memberdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of the original file bytes.', max_length=64),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='compressed_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size of the stored compressed bytes.', null=True),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(help_text='Original uncompressed file size in bytes.'),
        ),
    ]
