# Generated by Django 5.0.14 on 2026-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_memberdocument_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdocument',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of the original file bytes.', max_length=64, null=True),
        ),
    ]
