# Generated by Django 5.0.14 on 2026-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_baseaccount_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
