# Generated by Django 5.0.14 on 2026-07-23 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_member_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='absolute_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='authsession',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='authsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authsession',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authsession',
            name='token_family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='authsession',
            name='user_agent_summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['token_family_id'], name='account_session_family_idx'),
        ),
    ]
