# Generated by Django 5.0.14 on 2026-07-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_authsession_absolute_expires_at_and_more'),
        ('core', '0038_remove_assignmentrule_department_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designation',
            name='unique_department_designation_code',
        ),
        migrations.RemoveField(
            model_name='staffaccessscope',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminaccessscope',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='designation',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
