# Generated by Django 5.0.14 on 2026-07-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_staffaccessscope_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customersupportactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customersupportactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='memberactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='memberactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='superadminactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='superadminactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
