# Generated by Django 5.0.14 on 2026-07-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_adminactivitylog_actor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupportactivitylog',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='customersupportactivitylog',
            name='actor_role',
        ),
        migrations.RemoveField(
            model_name='memberactivitylog',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='memberactivitylog',
            name='actor_role',
        ),
        migrations.RemoveField(
            model_name='staffactivitylog',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='staffactivitylog',
            name='actor_role',
        ),
    ]
