# Generated by Django 5.0.14 on 2026-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_customersupportactivitylog_actor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivitylog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='memberactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
