# Generated by Django 5.0.14 on 2026-07-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_adminactivitylog_city_adminactivitylog_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='account',
        ),
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customersupportaccessscope',
            name='state',
        ),
        migrations.DeleteModel(
            name='CustomerSupportActivityLog',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='created_by_admin',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='manager_admin',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='customersupportagent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customersupportloginactivity',
            name='customer_support_agent',
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='code',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='authchallenge',
            name='account_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='account_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomerSupportAccessScope',
        ),
    ]
