# Generated by Django 5.0.14 on 2026-07-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_customersupportaccessscope_account_and_more'),
        ('core', '0040_remove_notification_notification_exactly_one_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSupportAgent',
        ),
        migrations.DeleteModel(
            name='CustomerSupportLoginActivity',
        ),
    ]
