# Generated by Django 5.0.14 on 2026-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_delete_customersupportagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='code',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='authchallenge',
            name='account_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='account_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], db_index=True, max_length=30),
        ),
    ]
