# Generated by Django 5.0.14 on 2026-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_admin_admin_id_admin_bio_admin_photo_staff_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
